name: church_attendance
description: تطبيق حضور وغياب كنيسة
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.2.3
  supabase_flutter: ^2.8.0
  intl: ^0.19.0
  google_fonts: ^6.0.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  provider: ^6.0.5
  equatable: ^2.0.5
  cached_network_image: ^3.3.0



dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
